In [26]:
import numpy as np

In [27]:
import math

In [2]:
A = np.array([[1,3,3],[2,6,9],[-1,-3,3]])
A

array([[ 1,  3,  3],
       [ 2,  6,  9],
       [-1, -3,  3]])

#### Transpose

In [3]:
A.T

array([[ 1,  2, -1],
       [ 3,  6, -3],
       [ 3,  9,  3]])

#### Access the shape, size and column

In [ ]:
np.shape(A)

In [ ]:
A.size

In [ ]:
A[:,1]

#### Dot Product, Length and Unit Vectors

The dot product or inner product of v and w is 
$$ v = (v_1, v_2) \ \ w = (w_1, w_2) $$
$$ v \cdot w = v_1w_1 + v_2w_2 $$

The vectors v = (4,2) and w = (-1, 2) have zero dot product:


$$\begin{bmatrix} 4 \\ 2 \end{bmatrix} \cdot \begin{bmatrix} -1 \\ 2 \end{bmatrix} = -4 + 4 = 0 $$


This means that these two vectors are perpendicular to eachother

In [31]:
v = np.array([4,2])
w = np.array([-1,2])
np.vdot(v,w)

0

 The length ||v|| of a vector v is defined as
 $$ length = ||v|| = \sqrt{v \cdot v} = (v^2_1 + v^2_2 + \cdot\cdot\cdot + v^2_n)^{1/2} $$

In [16]:
b = np.array([[1,5,5]])
b

array([[1, 5, 5]])

In [17]:
np.linalg.norm(b) # np uses the .linalg.norm method to find the length

7.14142842854285

In [32]:
np.vdot(b,b) # for matrix multiplication use the .vdot method

51

In [28]:
math.sqrt(51) # square root of the dot product of b

7.14142842854285

A unit vector u is a vector whose length equals one. Then 
$$ u = \frac{v}{||v||} = 1 $$

#### Matrices

$$ A = \begin{bmatrix} 1 \ \ 2 \\ 3 \ \ 4 \\ 5 \ \ 6 \end{bmatrix} is \ a \ 3 \ by \ 2 \ matrix: \ m \ = \ 3 \ rows \ and \ n = 2 \ columns$$


$$ Ax=\begin{bmatrix} 1 \ \ 2 \\ 3 \ \ 4 \\ 5 \ \ 6 \end{bmatrix}\begin{bmatrix} x_1 \\ x_2 \end{bmatrix} $$
Is a combinations of the columns
$$ Ax= x_1 \begin{bmatrix} 1 \\ 3 \\ 5 \end{bmatrix}+ x_2 \begin{bmatrix} 2 \\ 4 \\ 6 \end{bmatrix} $$

The three components of Ax are dot products of the 3 rows of A with the vector x:
$$ Row \ at \ a \ time \ \ \ \ \ \begin{bmatrix} 1 \ \ 2 \\ 3 \ \ 4 \\ 5 \ \ 6 \end{bmatrix}\begin{bmatrix} 7 \\ 8 \end{bmatrix} = \begin{bmatrix} 1 \cdot 7 + 2 \cdot 8 \\ 3 \cdot 7 + 4 \cdot 8 \\ 5 \cdot 7 + 6 \cdot 8 \end{bmatrix} = \begin{bmatrix} 23 \\ 53 \\ 83 \end{bmatrix}$$

$$ Equations \ in \ matrix \ form \ Ax = b: \begin{bmatrix} 2 \ \ 5 \\ 3 \ \ 7 \end{bmatrix}\begin{bmatrix} x_1 \\ x_2 \end{bmatrix} = \begin{bmatrix} b_1 \\ b_2 \end{bmatrix} $$ replaces $$ 2x_1 + 5x_2 = b_1 $$ $$3x_1 + 7x_2 = b_2 $$ 

$$ The \ solution \ to \ Ax = b \ can \ be \ written \ as \ x = A^{-1}b. But \ some \ matrices \ don \ not \ allow \ A^{-1} $$

### Solving Systems of Equations

In [21]:
A2 = np.array([[1,3,3],[2,6,9],[0,5,1]])

In [22]:
b = np.array([[1,5,5]])

In [23]:
b2 = np.transpose(b)
b2

array([[1],
       [5],
       [5]])

In [24]:
x,y,z = np.linalg.solve(A2,b2)
print(f'x = {x[0]} \ny = {y[0]} \nz = {z[0]}')

x = -4.4 
y = 0.8 
z = 1.0


The inverse of a matrix is another matrix, which by multiplying with the given matrix gives the identity matrix. The inverse of a matrix is used of find the solution of linear equations through the matrix inversion method.  But not all matrix can be inverted.  A singular matrix is a square matrix who's determinant is zero.

In [4]:
try:
    np.linalg.inv(A)
except Exception as e:
    print(f'It is a {e}')

It is a Singular matrix


#### Determinants

We know this because the determinant is zero

In [5]:
np.linalg.det(A)

0.0

The idea of the determinant is to get an indication of whether a system of equations has exactly one solution, or not. If the determinant is zero, then the system has no solutions, or many solutions. Otherwise, it has exactly one.

The reason it works out this way is that the determinant formula is set up to give zero if the columns are not linearly independent. If the columns are not linearly independent, that means we don't have enough information to find a unique solution.

Linear dependence between columns means that at least one of the columns is a linear combination of the others. This is a formal way of saying that one of the columns doesn't provide any new information because it's derived by adding together other columns (possibly after multiplying them by constants first.) 

In [7]:
np.linalg.det(A2)

-14.999999999999993

In [36]:
A2_inv = np.linalg.inv(A2)
A2_inv

array([[ 2.6       , -0.8       , -0.6       ],
       [ 0.13333333, -0.06666667,  0.2       ],
       [-0.66666667,  0.33333333, -0.        ]])

In [37]:
A2

array([[1, 3, 3],
       [2, 6, 9],
       [0, 5, 1]])

In [38]:
np.dot(A2, A2_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

However, order matters

In [40]:
np.dot(A2_inv, A2) == np.dot(A2, A2_inv)

array([[ True, False, False],
       [ True,  True, False],
       [ True,  True,  True]])

In [15]:
I = np.array([[4,1],[3,1]])
I2 = np.array([[1,-1],[-3,4]]) # the inverse of I
I, I2

(array([[4, 1],
        [3, 1]]),
 array([[ 1, -1],
        [-3,  4]]))

In [11]:
np.linalg.inv(I)

array([[ 1., -1.],
       [-3.,  4.]])

In [12]:
np.dot(I, I2)

array([[1, 0],
       [0, 1]])

In [34]:
np.dot(I, I2) == np.dot(I2, I)

array([[ True,  True],
       [ True,  True]])